research_task:
  description: >
    Find the top most interesting CVEs reported in {security_vulnerabilities_url}. 
    For each of the CVE you select, you should extract the following information:
    1) CVE ID (e.g: CVE-2025-12345)
    2) Type of Vulnerability (e.g: RCE, SQL Injection, etc.)
    3) CVE Publication Date (e.g: 2025-01-01)
    4) Link to the CVE vulnerability page (e.g: https://security.snyk.io/vuln/SNYK-JS-KIBANA-10339388). The link exists as the href attribute of the anchor tag in the HTML page, set on the name of the vulnerability.
    5) Package name that was found vulnerable (e.g: kibana)
  
  expected_output: >
    A total of 3 CVEs, each formatted as a bullet point in the following markdown format (strict markdown formatting for example links should not have space between the [] and () chars):
    ```
    **@trpc/server** found vulnerable to CVE-2025-43855 [Uncaught Exception](https://security.snyk.io/vuln/SNYK-JS-TRPCSERVER-10060256), 24 Apr 2025
    ```
  agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
